workspace = { members = ["derive-weight"] }

[package]
name = "weight-decorator"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
derive-weight = { path="./derive-weight" }
frame-support = "29.0.0"
