workspace = { members = ["weight-decorator-derive"] }
[package]
name = "weight-decorator"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
weight-decorator-derive = { path="weight-decorator-derive" }
frame-support = "29.0.0"
