[package]
name = "weight-decorator-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.50", features = [ "full" ] }
quote = "1.0.35"
frame-support = "29.0.0"
